area/binary:
  - 'main.go'
area/internal:
  - 'internal/**/*'
area/library:
  - 'pkg/**/*'
area/infra:
  - '.github/**/*'
  - 'Makefile'
  - '.goreleaser.yml'
  - '.golangci.yml'
area/deps:
  - 'go.mod'
  - 'go.sum'
area/docs:
  - 'README.md'
area/testing:
  - '**/*_test.go'
  - '**/testdata/**/*'
