name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
      id: go

    - name: Cache go module cache
      id: cache-go-mod
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: make test-all
    
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Lint
      run: make lint

  go-apidiff:
    name: go-apidiff
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Run go-apidiff
      uses: joelanford/go-apidiff@main
